services:
  - type: web
    name: campus-event
    runtime: docker
    region: singapore
    plan: free
    healthCheckPath: /api/auth/test
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: render
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: APP_SEED_ENABLED
        value: "true"
      - key: DEMO_ADMIN_PASSWORD
        sync: false
      - key: DEMO_DEPARTMENT_PASSWORD
        sync: false
      - key: DEMO_COMMITTEE_PASSWORD
        sync: false
      - key: DEMO_STUDENT_PASSWORD
        sync: false
      - key: SMTP_USERNAME
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URI
        sync: false
      - key: GOOGLE_OAUTH_SCOPES
        value: "openid,profile,email,https://www.googleapis.com/auth/forms.body,https://www.googleapis.com/auth/forms.responses.readonly,https://www.googleapis.com/auth/drive.file"
      - key: APP_PUBLIC_BASE_URL
        sync: false
