USE [event_management_db];
GO

SET NOCOUNT ON;

DECLARE @as_of_end DATETIME2(0) = '2026-05-20T00:00:00';

-- A proposal that has been published is no longer an active proposal workflow item.
IF OBJECT_ID('dbo.eventProposal', 'U') IS NOT NULL
BEGIN
    DELETE FROM dbo.eventProposal
    WHERE status = 'PUBLISHED';
END;

IF OBJECT_ID('dbo.event_proposal', 'U') IS NOT NULL
BEGIN
    DELETE FROM dbo.event_proposal
    WHERE status = 'PUBLISHED';
END;

-- Remove duplicate events generated by repeated publish clicks when no registrations exist.
;WITH duplicate_events AS (
    SELECT
        id,
        ROW_NUMBER() OVER (
            PARTITION BY title, start_time, department_id
            ORDER BY id
        ) AS rn
    FROM dbo.event
)
DELETE e
FROM dbo.event e
JOIN duplicate_events d ON d.id = e.id
WHERE d.rn > 1
  AND NOT EXISTS (
      SELECT 1
      FROM dbo.registration r
      WHERE r.event_id = e.id
  );

-- Keep event windows valid.
UPDATE dbo.event
SET end_time = DATEADD(HOUR, 2, start_time)
WHERE end_time <= start_time;

-- Align event status with the 2026-05-19 business date.
UPDATE dbo.event
SET status = 'COMPLETED'
WHERE end_time < @as_of_end
  AND status <> 'CANCELLED';

UPDATE dbo.event
SET status = 'PUBLISHED'
WHERE start_time >= @as_of_end
  AND status = 'COMPLETED';

-- Operational rows must not be in the future relative to 2026-05-19.
DELETE f
FROM dbo.feedback f
JOIN dbo.event e ON e.id = f.event_id
WHERE f.created_at >= @as_of_end
   OR e.start_time >= @as_of_end;

DELETE a
FROM dbo.attendance a
JOIN dbo.registration r ON r.id = a.registration_id
JOIN dbo.event e ON e.id = r.event_id
WHERE a.checkin_time >= @as_of_end
   OR e.start_time >= @as_of_end;

DELETE FROM dbo.ticket
WHERE sent_date >= @as_of_end;

IF OBJECT_ID('dbo.emailLog', 'U') IS NOT NULL
BEGIN
    EXEC sp_executesql
        N'DELETE FROM dbo.emailLog WHERE sent_at >= @asOf',
        N'@asOf DATETIME2(0)',
        @asOf = @as_of_end;
END;

IF OBJECT_ID('dbo.email_log', 'U') IS NOT NULL
BEGIN
    EXEC sp_executesql
        N'DELETE FROM dbo.email_log WHERE sent_at >= @asOf',
        N'@asOf DATETIME2(0)',
        @asOf = @as_of_end;
END;

DELETE FROM dbo.activity_log
WHERE created_at >= @as_of_end;

SELECT
    (SELECT COUNT(*) FROM dbo.event) AS events,
    (SELECT COUNT(*) FROM dbo.registration WHERE registration_date < @as_of_end) AS registrations_as_of,
    (SELECT COUNT(*) FROM dbo.attendance WHERE checkin_time < @as_of_end) AS attendance_as_of,
    (SELECT COUNT(*) FROM dbo.feedback WHERE created_at < @as_of_end) AS feedback_as_of;
GO
